name: Build

on:
    pull_request:
    push:
        branches:
            - "!master"

permissions:
  contents: write
  pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run build
            - run: npm run format
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "chore: format code"
                  branch: ${{ github.head_ref }}
