name: Ponyfinder Foundry Release Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get Version              # Run the script that returns the version from `module.json`
      shell: bash
      id: get-version
      run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
    - name: Build module.json
      run: node ./.github/workflows/build-module-json.js | jq . > module.json
    - name: Create Release Zip
      run: zip -r ./ponyfinder-foundryvtt-module.zip module.json assets packs       # Add folders/files here
    - name: Create Latest Release
      id: create_latest_release
      uses: ncipollo/release-action@v1
      if: endsWith(github.ref, 'main') # Only update the latest release when pushing to the master branch
      with:
        allowUpdates: true
        name: Latest
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./ponyfinder-foundryvtt-module.zip'  # don't forget to rename module zip thing
        tag: latest
