name: Release

on:
    push:
        branches:
            - master

permissions:
    contents: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run build
            - run: npm run format
            # - uses: calibreapp/image-actions@main
            #   with:
            #     githubToken: ${{ secrets.GITHUB_TOKEN }}
            #     ignorePaths: '.parcel-cache/**,node_modules/**,src/**'
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "chore: format code"
                  branch: ${{ github.head_ref }}
            - name: Get Version
              id: get_version
              run: |
                  content=`cat ./module.json`
                  # the following lines are only required for multi line json
                  content="${content//'%'/'%25'}"
                  content="${content//$'\n'/'%0A'}"
                  content="${content//$'\r'/'%0D'}"
                  # end of optional handling for multi line json
                  echo "::set-output name=moduleJson::$content"
            - name: Create Release Zip
              run: zip -r ./ponyfinder-foundryvtt-module.zip module.json dist/assets dist/packs dist/scripts lang
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "./module.json,./ponyfinder-foundryvtt-module.zip"
                  tag: v${{ fromJson(steps.get_version.outputs.moduleJson).version }}
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Update Latest
              uses: ncipollo/release-action@v1
              with:
                  allowUpdates: true
                  artifacts: "./module.json,./ponyfinder-foundryvtt-module.zip"
                  tag: latest
                  token: ${{ secrets.GITHUB_TOKEN }}
