name: Create Archive
on: [push]
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git* *.md *.yml'
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        # Artifact name
        name: 'ponyfinder-foundryvtt-module'
        # A file, directory or wildcard pattern that describes what to upload
        path: './'
